version: '3.4'

services:
  php:
    build: ./docker/php
    container_name: php-foot
    volumes:
      - ./:/app

  nginx:
    image: nginx:1.17.5
    container_name: nginx-foot
    ports:
      - '8000:80'
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./:/srv/application
      - ./var/log/nginx:/var/log/nginx
    depends_on:
      - php

  db:
    image: mysql:5.7
    container_name: db-foot
    ports:
      - '3308:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 'secret-root'
      MYSQL_DATABASE: 'wanafoot'
      MYSQL_USER: 'wanadev'
      MYSQL_PASSWORD: 'secret'
    volumes:
      - db:/var/lib/mysql

volumes:
  db: {}